---
- hosts: webservers
  become: true
 
  tasks:
  - name: remove openJDK java
    apt:
      name:  openjdk-8-jdk
      state: absent
      autoremove: yes
      purge: yes

  - name: SET JAVA_HOME
    shell: sudo echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> ~/.bashrc

