---
- hosts: webservers
  become: true
 
  tasks:

  - name: Installation on packages
    apt:
      name:  "{{ item }}"
      state: present
    loop:
      - mongodb
      - zip
      - unzip
      - vsftpd
 
  - name: Check mongodb version
 
    command: mongo -version
    register: mongodb_version
 
  - debug:
      msg: “{{ mongodb_version.stdout }}”
