---
- hosts: webservers
  become: true
 
  tasks:
  - name: Installation on packages
    apt:
      name:  "{{ item }}"
      state: present
    loop:
      - mongodb
      - zip
      - unzip
      - vsftpd

