---
# tasks file for web-server
    - name: install apache2
      apt:
        name: "{{apachepakagename}}"
        update_cache: yes      
        state: latest
 
    - name: Copy index page
      copy:
        src: "{{webcontent}}"
        dest: "{{wwwpath}}"
    - name: Update apache configuration
      template:
        src: ports.j2
        dest: /etc/apache2/ports.conf
      notify:
        - restart apache2


