---
# tasks file for web-server
    - name: install apache2
      apt:
        name: "{{apachepakagename}}"
        state: latest
 
    - name: enabled mod_rewrite
      apache2_module:
        name: rewrite
        state: present
      notify:
         - restart apache2
 
    - name: Copy index page
      copy:
        src: "{{webcontent}}"
        dest: "{{wwwpath}}"
 

